export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST'
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS'
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE'

export const POST_SERVICE_REQUEST = 'POST_SERVICE_REQUEST'
export const POST_SERVICE_FAILURE = 'POST_SERVICE_FAILURE'

export const EDIT_SERVICE_REQUEST = 'EDIT_SERVICE_REQUEST'
export const EDIT_SERVICE_FAILURE = 'EDIT_SERVICE_FAILURE'

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST'
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE'
